(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(backup-directory-alist (quote ((".*" . "/tmp/"))))
 '(blink-cursor-mode nil)
 '(c-basic-offset 4)
 '(c-default-style "bsd")
 '(completion-styles (quote (basic partial-completion emacs22 initials)))
 '(cua-enable-cua-keys nil)
 '(cua-mode t nil (cua-base))
 '(default-frame-alist (quote ((line-spacing . 2))))
 '(diary-file "~/Dropbox/org/diary")
 '(dynamic-completion-mode t)
 '(ediff-split-window-function (quote split-window-horizontally))
 '(font-use-system-font t)
 '(gdb-many-windows t)
 '(global-auto-revert-mode t)
 '(global-hl-line-mode t)
 '(gud-gdb-command-name "gdb -i=mi")
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(large-file-warning-threshold nil)
 '(make-backup-files nil)
 '(menu-bar-mode nil)
 '(org-agenda-files (quote ("~/Dropbox/org/")))
 '(org-babel-load-languages (quote ((emacs-lisp . t) (calc . t))))
 '(org-export-creator-info nil)
 '(org-export-default-language "kr")
 '(org-export-email-info t)
 '(org-export-headline-levels 2)
 '(org-export-html-validation-link "")
 '(org-export-section-number-format (quote ((("1" ".")) . "")))
 '(org-log-done (quote time))
 '(org-startup-indented t)
 '(password-cache-expiry 900)
 '(recentf-mode t)
 '(safe-local-variable-values (quote ((dired-omit-mode . t))))
 '(scroll-bar-mode nil)
 '(send-mail-function (quote smtpmail-send-it))
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(split-height-threshold nil)
 '(split-width-threshold 140)
 '(tab-always-indent (quote complete))
 '(tab-width 4)
 '(text-mode-hook (quote (text-mode-hook-identify)))
 '(tool-bar-mode nil)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(use-file-dialog nil)
 '(user-full-name "SeungKi Kim")
 '(user-mail-address "tttuuu888@gmail.com"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
